name: Auto-generate category JSONs

on:
  workflow_dispatch:  # ✅ Permette l'avvio manuale
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.JPG'
      - '**.PNG'
      - '**.JPEG'
      - 'scripts/generate_json.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          pip install colorthief webcolors

      - name: Generate JSON files
        run: python scripts/generate_json.py

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Auto update JSON for new wallpapers" || echo "No changes"
          git push
