name: Genera JSON da R2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # esegue ogni giorno a mezzanotte
  push:
    paths:
      - 'scripts/json_cloudflare.py'
      - 'scripts/generate_master_json.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Esegui script per generare JSON per categoria
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: python scripts/json_cloudflare.py

      - name: Unifica in cloudflare_master.json
        run: python scripts/generate_master_json.py

      - name: Commit e push dei file JSON generati
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cloudflare_*.json
          git commit -m "Aggiorna JSON da R2" || echo "Nessuna modifica"
          git push
